export const TYPES = {
  Bot: Symbol.for('Bot'),
  Config: Symbol.for('Config'),
  Client: Symbol.for('Client'),
  Command: Symbol.for('Command'),
  Event: Symbol.for('Event'),
  CommandManager: Symbol.for('CommandManager'),
  CommandService: Symbol.for('CommandService'),
  AutoModService: Symbol.for('AutoModService'),
  DatabaseManager: Symbol.for('DatabaseManager'),
  EventManager: Symbol.for('EventManager'),
  PunishmentService: Symbol.for('PunishmentService'),
  TimeoutsManager: Symbol.for('TimeoutsManager'),
  GuildSettingsService: Symbol.for('GuildSettings'),
  BotListService: Symbol.for('BotListService'),
  StatusManager: Symbol.for('StatusManager'),
  CommandStatisticsManager: Symbol.for('CommandStatisticsManager'),
  UserSettingsService: Symbol.for('UserSettings'),
  GuildCounterManager: Symbol.for('GuildCounterManager'),
  LocalizationManager: Symbol.for('LocalizationManager'),
  CaseSettingsService: Symbol.for('CaseSettingsService'),
  WarningService: Symbol.for('WarningService')
};
