#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'nino - ❓ lint ~ ❓ project - checking eslint for errors'
eslint src --ext .ts # `--fix` would normally be here but it should only print and not fix

echo 'nino - ✔ lint ~ ❓ project - compiling project for errors'
yarn tsc --noEmit

echo 'nino - ✔ lint ~ ✔ project - we are done here'
